### ISSUE TITLE
Too much documentation moved to "Deprecated Modules"

### ISSUE THREAD

**Issue by senarvi** [Lightning-AI/lightning-bolts#798]
Documentation for all the models, including "How to use models", was moved under "Deprecated Modules" in pull request https://github.com/PyTorchLightning/lightning-bolts/pull/722 . Deprecating SSL implementations was discussed in issue https://github.com/PyTorchLightning/lightning-bolts/issues/712 . Issue https://github.com/PyTorchLightning/lightning-bolts/issues/719 discussed what would be deprecated and there indeed all models are listed as deprecated. According to @Borda , this is an error, and only SSL implementations should be deprecated. Notifying @SeanNaren .

**Comment by veriff-javiervgd** [comment]
I am really happy to hear it was a mistake, I thought all the models were going to be deprecated... so much effort gone to the trash if that was the case... nice to hear it is not the case :laughing:

**Comment by veriff-javiervgd** [comment]
Any  news on this?

**Comment by SeanNaren** [comment]
Hey @veriff-javiervgd, deprecated is the wrong word I think that was used, I think "community maintained" might be a better word.

The issue was that a LOT of models/datasets were unsupported and breaking (versions change of other libraries) and no one was maintaining them. Maybe we need to make it clearer somehow without being as destructive (have a note at the top of each page of which ones are currently unmaintained).

**Comment by veriff-javiervgd** [comment]
Mmm I understand, thank you for the clarification. I totally agree with you, a "community mantained" label with its corresponding warning would be fairer and more informative

**Comment by senarvi** [comment]
I think it would be a good idea to label those breaking models that are not maintained, or even remove them, but it's not necessary to deprecate every model.
