### ISSUE TITLE
AttributeError: `BinaryMNISTDataModule` object has no attribute `train_transforms`

### ISSUE THREAD

**Issue by davidgilbertson** [Lightning-AI/lightning-bolts#934]
### To Reproduce
Trying to run the code from the docs here: https://lightning-bolts.readthedocs.io/en/stable/datamodules/vision.html#binarymnist

Steps to reproduce the behavior: Run the code from that page:
```py
from pl_bolts.datamodules import BinaryMNISTDataModule

dm = BinaryMNISTDataModule('.')
model = LitModel()

Trainer().fit(model, datamodule=dm)
```

### Expected behavior
It shouldn't error :)

### Environment
pytorch-lightning: 1.7.7
lightning-bolts: 0.5.0

### Additional context
Adding this makes it work:
```py
dm = BinaryMNISTDataModule(".")
dm.train_transforms = None
dm.val_transforms = None
...
```

This check (and the `val` counterpart) are assuming the existence of an attribute that isn't defined as a default.
```py
train_transforms = self.default_transforms() if self.train_transforms is None else self.train_transforms
```
From https://github.com/Lightning-AI/lightning-bolts/blob/master/pl_bolts/datamodules/vision_datamodule.py#L103

I don't know the codebase well, but it looks like either `train_transforms` should have a default value, or a `hasattr()` check should be added, or query the value with a fallback, like `if getattr(self, 'train_transforms', None) is None`

Or maybe I'm doing something wrong. The docs have this cryptic little message about transforms, with no context. What is this saying, what is `transform_lib`, what am I supposed to do with `mnist_transforms`?

![image](https://user-images.githubusercontent.com/4443482/199611226-c452a7d2-8f1b-451d-8c63-b10c4b204610.png)

**Comment by otaj** [comment]
Hi, @davidgilbertson. This is happening because `pytorch-lightning>=1.7.0` removed these methods and `lightning-bolts==0.5.0` was released quite some time ago.

If you update to `lightning-bolts==0.6.0`, this should be fixed. We made sure we're being a bit more compatible with current version.

OTOH, beware please, that if you use 0.6.0, you will get quite a bit of warnings originating from our package, this is mainly due to issue #839. They should be harmless, but there will be quite many of them
